name: Sellza Sniper Bot 🎯

on:
  workflow_dispatch: # زرار تشغيل يدوي
  schedule:
    - cron: '0 8 * * *' # هيشتغل لوحده كل يوم الساعة 10 الصبح بتوقيت مصر

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx puppeteer browsers install chrome
      - run: node index.js
