name: Sniper Daily Auto Run

on:
  schedule:
    # الساعة 11 مساءً بتوقيت جرينتش تساوي الساعة 1 صباحاً بتوقيت مصر
    - cron: "0 23 * * *"
  workflow_dispatch: # يتيح لك تشغيل البوت يدوياً أيضاً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        env:
          # ربط الـ Secrets التي أدخلتها بالمتغيرات التي يقرأها الكود
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SELLZA_EMAIL: ${{ secrets.SELLZA_EMAIL }}
          SELLZA_PASS: ${{ secrets.SELLZA_PASS }}
          BOSAT_USER: ${{ secrets.BOSAT_USER }}
          BOSAT_PASS: ${{ secrets.BOSAT_PASS }}
          START: ${{ secrets.START }}
          END: ${{ secrets.END }}
        run: node index.js
